language: cpp
dist: bionic
notifications:
  email: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - lcov
            - g++-7
            - libsdl2-2.0-0
            - libsdl2-dev
      env:
        - MATRIX_EVAL="CXX_COMPILER=g++-7; sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-7 90"

    - os: osx
      osx_image: xcode10.1
      addons:
        homebrew:
          packages:
          - lcov
          - sdl2
      env:
        - MATRIX_EVAL="CXX_COMPILER=clang++"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - gem install coveralls-lcov

before_script:
  - PARENTDIR=$(pwd)
  - mkdir -p $PARENTDIR/build && cd $PARENTDIR/build

script:
  - cd $PARENTDIR/build
  - cmake -DCMAKE_BUILD_TYPE=Coverage $PARENTDIR
  - make
  - make gtest
